FROM node:16-alpine as build

ARG REACT_APP_METACOM_PORT
ENV REACT_APP_METACOM_PORT=$REACT_APP_METACOM_PORT

WORKDIR /app
COPY . .
RUN apk add --no-cache python3 \
        make \
        g++ 
RUN npm ci
WORKDIR /app/frontend
ENV GENERATE_SOURCEMAP=false
RUN npm run build

FROM nginx
COPY --from=build /app/frontend/build /usr/share/nginx/html
COPY --from=build /app/frontend/nginx.conf /etc/nginx/conf.d/default.conf
