FROM node:16-alpine as build
WORKDIR /app/backend
COPY . .
RUN apk add --no-cache python3 \
        make \
        g++
RUN npm ci
# RUN npm ci --only=production
# RUN npm ci --omit=dev
# FROM node:16-alpine
# COPY --from=build /app /app
WORKDIR /app/backend
CMD node server.js
