({
    defs: [
        //////////// Marine /////////////
        {
            biome: 'Glacier',
            height: [-1, 0],
            temperature: [-1, -0.75],
            color: '#65C2FA',
        },
        {
            biome: 'Abyss',
            height: [-1, -0.9],
            temperature: [-0.75, 1],
            color: '#350786',
        },
        {
            biome: 'Deep Water',
            height: [-0.9, -0.7],
            temperature: [-0.75, 1],
            color: '#072A86',
        },
        {
            biome: 'Water',
            height: [-0.7, -0.3],
            temperature: [-0.8, 1],
            color: '#1444C4',
        },
        {
            biome: 'Swallow Water',
            height: [-0.3, 0],
            temperature: [-0.75, 1],
            color: '#1481CC',
        },
        {
            biome: 'Coral Reef',
            height: [-0.35, -0.15],
            temperature: [0.5, 1],
            moisture: [-0.5, 0.5],
            color: '#826BF6',
        },
        //////////// Polar /////////////
        {
            biome: 'Polar desert',
            height: [0, 1],
            temperature: [-1, -0.75],
            color: '#FFFFFF',
        },
        {
            biome: 'Ice peaks',
            height: [0.7, 1],
            temperature: [-1, -0.3],
            moisture: [-1, -0.5],
            color: '#B4B3B2',
        },
        {
            biome: 'Mountain Tundra',
            height: [0.7, 1],
            temperature: [-0.75, -0.6],
            moisture: [-0.5, 1],
            color: '#4A6E4A',
        },
        {
            biome: 'Alpine Meadow',
            height: [0.7, 0.8],
            temperature: [-0.5, -0.3],
            moisture: [-0.5, 0.5],
            color: '#5C835B',
        },
        {
            biome: 'Polar Plains',
            height: [0, 1],
            temperature: [-0.75, -0.3],
            moisture: [-1, 0.5],
            color: '#9DF841',
        },
        {
            biome: 'Tundra',
            height: [0, 1],
            temperature: [-0.75, -0.6],
            moisture: [-0.5, 1],
            color: '#5C835B',
        },
        {
            biome: 'Taiga',
            height: [0, 1],
            temperature: [-0.6, -0.5],
            moisture: [-0.5, 1],
            color: '#44943D',
        },
        {
            biome: 'Boreal Forest',
            height: [0, 1],
            temperature: [-0.5, -0.3],
            moisture: [-0.5, 1],
            color: '#4AB141',
        },
        //////////// Subtropical /////////////
        {
            biome: 'Grassland',
            height: [0, 1],
            temperature: [-0.3, 0.5],
            moisture: [-1, -0.5],
            color: '#9DF841',
        },
        {
            biome: 'Shrubland',
            height: [0, 1],
            temperature: [-0.3, 0.5],
            moisture: [-0.5, 0],
            color: '#99F16D',
        },
        {
            biome: 'Woodland',
            height: [0, 1],
            temperature: [-0.3, 0.5],
            moisture: [0, 0.5],
            color: '#4ECE19',
        },
        {
            biome: 'Subtropical Forest',
            height: [0, 1],
            temperature: [-0.3, 0.5],
            moisture: [0.5, 0.8],
            color: '#3CC006',
        },
        {
            biome: 'Subtropical Rainforest',
            height: [0, 1],
            temperature: [-0.3, 0.5],
            moisture: [0.8, 0.95],
            color: '#32A304',
        },
        {
            biome: 'Swamp',
            height: [0, 1],
            temperature: [-0.3, 0.5],
            moisture: [0.95, 1],
            color: '#32A304',
        },
        //////////// Tropical /////////////
        {
            biome: 'Extreme Desert',
            height: [0.15, 1],
            temperature: [0.8, 1],
            moisture: [-1, -0.5],
            color: '#FA980A',
        },
        {
            biome: 'Tropical Desert',
            height: [0.15, 1],
            temperature: [0.5, 0.8],
            moisture: [-1, -0.5],
            color: '#FDED49',
        },
        {
            biome: 'Savanna',
            height: [0.15, 1],
            temperature: [0.5, 1],
            moisture: [-0.5, 0],
            color: '#BE9A3C',
        },
        {
            biome: 'Tropical Forest',
            height: [0.15, 1],
            temperature: [0.5, 1],
            moisture: [0, 0.5],
            color: '#449E1F',
        },
        {
            biome: 'Tropical Rainforest',
            height: [0.15, 1],
            temperature: [0.5, 1],
            moisture: [0.5, 0.9],
            color: '#2B9002',
        },
        {
            biome: 'Tropical Swamp',
            height: [0.15, 1],
            temperature: [0.5, 1],
            moisture: [0.9, 1],
            color: '#226E03',
        },
        // {
        //     biome: 'Beach',
        //     height: [0, 0.15],
        //     temperature: [0.5, 1],
        //     color: '#CCCF70',
        // },
        //////////// Generic /////////////
    ],
})